import type { EntriesResponse, Entry } from '../types';

export const mockEntries: EntriesResponse = {
  total: 1,
  entries: [
    {
      id: 1,
      user_id: 1,
      feed_id: 1,
      status: 'read',
      hash: 'hash',
      title: 'title',
      url: 'url',
      comments_url: 'comments_url',
      published_at: 'published_at',
      created_at: 'created_at',
      content: 'content',
      author: 'author',
      share_code: 'share_code',
      reading_time: 5,
      starred: false,
      feed: {
        id: 1,
        user_id: 1,
        feed_url: 'feed_url',
        site_url: 'site_url',
        title: 'feed_title',
        checked_at: 'checked_at',
        next_check_at: 'next_check_at',
        etag_header: 'etag_header',
        last_modified_header: 'last_modified_header',
        parsing_error_message: 'parsing_error_message',
        parsing_error_count: 0,
        scraper_rules: 'scraper_rules',
        rewrite_rules: 'rewrite_rules',
        crawler: false,
        blocklist_rules: 'blocklist_rules',
        keeplist_rules: 'keeplist_rules',
        user_agent: 'user_agent',
        cookie: 'cookie',
        username: 'username',
        password: 'password',
        disabled: false,
        ignore_http_cache: false,
        fetch_via_proxy: false,
        category: {
          id: 1,
          title: 'category_title',
          user_id: 1,
        },
      },
      tags: [],
    },
  ],
};
